# Generated by Django 2.2 on 2019-04-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0002_auto_20190424_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
