# Generated by Django 2.2 on 2019-04-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0003_auto_20190424_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencys',
            },
        ),
    ]
