# Generated by Django 2.2 on 2019-04-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0004_currencys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currencys',
            new_name='Currency',
        ),
    ]
