# Generated by Django 2.2 on 2019-04-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0005_auto_20190426_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Code'),
        ),
    ]
