# Generated by Django 2.2 on 2019-04-26 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('legislation', '0006_auto_20190426_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='sites.Site')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
