# Generated by Django 2.2 on 2019-04-26 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0008_auto_20190426_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricesettings',
            options={'verbose_name': 'Price Settings', 'verbose_name_plural': 'Price Settings'},
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='disc_choice',
            field=models.BooleanField(default=False, verbose_name='Discont on two or more choices'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='disc_location',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)], verbose_name='Discount Location'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='disc_next_choice',
            field=models.BooleanField(default=False, verbose_name='Discont on every next choice'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='disc_next_location',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)], verbose_name='Discount Next Location'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='disc_next_topic',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)], verbose_name='Discount Next Topic'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='disc_topic',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)], verbose_name='Discount Topic'),
        ),
    ]
