# Generated by Django 2.2 on 2019-04-26 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0009_auto_20190426_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_location',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Discount Location'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_next_location',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Discount Next Location'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_next_topic',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Discount Next Topic'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_topic',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Discount Topic'),
        ),
    ]
