# Generated by Django 2.2 on 2019-04-26 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0010_auto_20190426_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='legislation.PriceSettings'),
        ),
    ]
