# Generated by Django 2.2 on 2019-04-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0011_currency_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='published',
        ),
        migrations.AddField(
            model_name='currency',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Main'),
        ),
    ]
