# Generated by Django 2.2 on 2019-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0012_auto_20190426_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='main',
            field=models.NullBooleanField(default=False, verbose_name='Default'),
        ),
    ]
