# Generated by Django 2.2 on 2019-04-26 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0014_auto_20190426_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_location',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Location'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_next_location',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Next Location'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_next_topic',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Next Topic'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='disc_topic',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Topic'),
        ),
        migrations.CreateModel(
            name='DiscountCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Description')),
                ('size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Topic')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcodes', to='legislation.PriceSettings')),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
            },
        ),
    ]
