# Generated by Django 2.2 on 2019-04-26 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0015_auto_20190426_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodes',
            name='size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Size'),
        ),
    ]
