# Generated by Django 2.2 on 2019-05-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0017_auto_20190509_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoint',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='location',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
