# Generated by Django 2.2 on 2019-08-06 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0018_auto_20190509_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price'),
        ),
    ]
