# Generated by Django 2.2 on 2019-08-06 04:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0019_auto_20190806_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='price',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='price',
        ),
        migrations.CreateModel(
            name='TopicCurrencyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencytopicprices', to='legislation.Currency')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicprices', to='legislation.Topic')),
            ],
            options={
                'verbose_name_plural': 'Topic prices',
                'verbose_name': 'Topic price',
                'unique_together': {('topic', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='LocationCurrencyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencylocationprices', to='legislation.Currency')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationprices', to='legislation.Location')),
            ],
            options={
                'verbose_name_plural': 'Location prices',
                'verbose_name': 'Location price',
                'unique_together': {('location', 'currency')},
            },
        ),
    ]
