# Generated by Django 2.2 on 2019-08-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0021_currencys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessesBuisnessActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name_plural': 'Processes and Business Activities',
                'verbose_name': 'Processe and Busines Activity',
            },
        ),
        migrations.CreateModel(
            name='Requirments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name_plural': 'Standard or Other Requirements',
                'verbose_name': 'Standard or Other Requirement',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name_plural': 'Sectors',
                'verbose_name': 'Sector',
            },
        ),
    ]
