# Generated by Django 2.2 on 2019-08-29 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20190821_0019'),
        ('legislation', '0022_processesbuisnessactivities_requirments_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legistation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=True, verbose_name='Published')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companylegislations', to='company.Company')),
            ],
            options={
                'verbose_name': 'Legislation',
                'verbose_name_plural': 'Legislations',
            },
        ),
        migrations.CreateModel(
            name='LegistationSpecQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('response', models.BooleanField(default=False, verbose_name='Yes/No')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companylegislations', to='legislation.Legistation')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionsresponses', to='legislation.Question')),
            ],
            options={
                'verbose_name': 'Legislation specific question',
                'verbose_name_plural': 'Legislation specific questions',
            },
        ),
    ]
