# Generated by Django 2.2 on 2019-08-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20190821_0019'),
        ('legislation', '0023_legistation_legistationspecquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegistationPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legislation specific question',
                'verbose_name_plural': 'Legislation specific questions',
            },
        ),
        migrations.CreateModel(
            name='LegistationSpecQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('response', models.BooleanField(default=False, verbose_name='Yes/No')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specquerypos', to='legislation.LegistationPosition')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionsresponses', to='legislation.Question')),
            ],
            options={
                'verbose_name': 'Legislation specific question',
                'verbose_name_plural': 'Legislation specific questions',
            },
        ),
        migrations.RenameModel(
            old_name='Legistation',
            new_name='Legislation',
        ),
        migrations.DeleteModel(
            name='LegistationSpecQuestions',
        ),
        migrations.AddField(
            model_name='legistationposition',
            name='legislation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislationpos', to='legislation.Legislation'),
        ),
        migrations.AddField(
            model_name='legistationposition',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationpos', to='legislation.Location'),
        ),
        migrations.AddField(
            model_name='legistationposition',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicpos', to='legislation.Topic'),
        ),
    ]
