# Generated by Django 2.2 on 2019-08-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0024_auto_20190829_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legistationposition',
            options={'verbose_name': 'Legislation position', 'verbose_name_plural': 'Legislation positions'},
        ),
    ]
