# Generated by Django 2.2 on 2019-08-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0025_auto_20190829_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
