# Generated by Django 2.2 on 2019-09-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0026_auto_20190830_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegistationSpecQuestionKeyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('response', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No'), (2, 'Partial')], max_length=10, null=True)),
                ('keypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specquerykeypoints', to='legislation.KeyPoint')),
                ('requirements', models.ManyToManyField(blank=True, to='legislation.KeyPointOption')),
                ('specquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specqueryposkeypoints', to='legislation.LegistationSpecQuestion')),
            ],
            options={
                'verbose_name': 'Legislation specific question',
                'verbose_name_plural': 'Legislation specific questions',
            },
        ),
    ]
