# Generated by Django 2.2 on 2019-09-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0027_legistationspecquestionkeypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keypoint',
            name='published',
        ),
        migrations.RemoveField(
            model_name='keypoint',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='location',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.CreateModel(
            name='LegislationTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=2000, verbose_name='Title')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leglocations', to='legislation.Location')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legtopics', to='legislation.Topic')),
            ],
            options={
                'verbose_name_plural': 'Legislation topics',
                'verbose_name': 'Legislation topic',
            },
        ),
        migrations.AddField(
            model_name='keypoint',
            name='legtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpoints', to='legislation.LegislationTopic'),
        ),
        migrations.AddField(
            model_name='question',
            name='legtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legquestions', to='legislation.LegislationTopic'),
        ),
    ]
