# Generated by Django 2.2 on 2019-09-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0028_auto_20190905_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypoint',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
