# Generated by Django 2.2 on 2019-09-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0030_auto_20190905_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legistationspecquestionkeypoint',
            name='response',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No'), (2, 'Partial')], null=True),
        ),
    ]
