# Generated by Django 2.2 on 2019-09-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0031_auto_20190905_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationTopicComply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Comply option',
                'ordering': ['title'],
                'verbose_name_plural': 'Comply option',
            },
        ),
        migrations.CreateModel(
            name='LegislationTopicOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Option',
                'ordering': ['option'],
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='LegistationTopicsResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('response', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No'), (2, 'Partial')], null=True)),
            ],
            options={
                'verbose_name': 'Legislation topic response',
                'verbose_name_plural': 'Legislation topic responses',
            },
        ),
        migrations.RemoveField(
            model_name='legistationspecquestionkeypoint',
            name='keypoint',
        ),
        migrations.RemoveField(
            model_name='legistationspecquestionkeypoint',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='legistationspecquestionkeypoint',
            name='specquestion',
        ),
        migrations.RemoveField(
            model_name='keypoint',
            name='comply',
        ),
        migrations.AddField(
            model_name='legislationtopic',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='legislationtopic',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='KeyPointOption',
        ),
        migrations.DeleteModel(
            name='LegistationSpecQuestionKeyPoint',
        ),
        migrations.AddField(
            model_name='legistationtopicsresponse',
            name='legtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ltopicreply', to='legislation.LegislationTopic'),
        ),
        migrations.AddField(
            model_name='legistationtopicsresponse',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='legislation.LegislationTopicOption'),
        ),
        migrations.AddField(
            model_name='legislationtopicoption',
            name='legtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='koptions', to='legislation.LegislationTopic'),
        ),
        migrations.AddField(
            model_name='legislationtopiccomply',
            name='legtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topcomply', to='legislation.LegislationTopic'),
        ),
    ]
