# Generated by Django 2.2 on 2019-09-06 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0032_auto_20190906_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationtopicsresponse',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.LegistationPosition'),
        ),
    ]
