# Generated by Django 2.2 on 2019-09-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0033_legistationtopicsresponse_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislationtopiccomply',
            name='legtopic',
        ),
        migrations.RemoveField(
            model_name='legislationtopicoption',
            name='legtopic',
        ),
        migrations.AddField(
            model_name='legislationtopiccomply',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topcomply', to='legislation.KeyPoint'),
        ),
        migrations.AddField(
            model_name='legislationtopicoption',
            name='comply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='koptions', to='legislation.LegislationTopicComply'),
        ),
    ]
