# Generated by Django 2.2 on 2019-09-10 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0036_legistationnonconformanceresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legistationnonconformanceresponse',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.SourceNC'),
        ),
    ]
