# Generated by Django 2.2 on 2019-09-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0038_auto_20190910_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislationtopic',
            name='nodescription',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='NC description'),
        ),
        migrations.AlterField(
            model_name='legislationtopic',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Full description'),
        ),
    ]
