# Generated by Django 2.2 on 2019-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0038_auto_20190910_0047'),
    ]

    operations = [
    ]
