# Generated by Django 2.2 on 2019-09-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0039_auto_20190911_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislationtopic',
            name='nodescription',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Non Conformance description'),
        ),
    ]
