# Generated by Django 2.2 on 2019-09-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0039_auto_20190911_0653'),
        ('legislation', '0040_auto_20190911_0120'),
    ]

    operations = [
    ]
