# Generated by Django 2.2 on 2019-09-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0041_merge_20190911_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='finished_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='started',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
