# Generated by Django 2.2 on 2019-09-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0042_auto_20190912_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislation',
            name='finished_date',
        ),
        migrations.AddField(
            model_name='legislation',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish date'),
        ),
    ]
