# Generated by Django 2.2 on 2019-09-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0043_auto_20190912_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('file', models.FileField(max_length=2000, upload_to='documents/%Y/%m/%d/', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Documents',
                'ordering': ['title'],
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
