# Generated by Django 2.2 on 2019-09-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0044_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
