# Generated by Django 2.2 on 2019-09-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0045_auto_20190912_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['title'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
