# Generated by Django 2.2 on 2019-09-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0046_auto_20190912_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=2000, upload_to='documents/%Y/%m/%d/', verbose_name='File'),
        ),
    ]
