# Generated by Django 2.2 on 2019-09-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0047_auto_20190912_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislation',
            options={'ordering': ['-finished'], 'verbose_name': 'Legislation', 'verbose_name_plural': 'Legislations'},
        ),
    ]
