# Generated by Django 2.2 on 2019-09-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0048_auto_20190912_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegistationDocumens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=2000, upload_to='legislation/documents/%Y/%m/%d/', verbose_name='File')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legdocs', to='legislation.Legislation')),
            ],
            options={
                'verbose_name_plural': 'Legislation positions',
                'verbose_name': 'Legislation position',
            },
        ),
    ]
