# Generated by Django 2.2 on 2019-09-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0051_auto_20190918_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
