# Generated by Django 2.2 on 2019-09-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0053_auto_20190924_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legistationtopicsresponse',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postopicresponses', to='legislation.LegistationPosition'),
        ),
    ]
