# Generated by Django 2.2 on 2019-09-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0054_auto_20190924_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='legistationdocument',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
