# Generated by Django 2.2 on 2019-09-25 06:04

from django.db import migrations

def set_pos(apps, schema_editor):
    LegistationTopicsResponse = apps.get_model("legislation", "LegistationTopicsResponse")
    for p in LegistationTopicsResponse.objects.all():
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0056_auto_20190925_0603'),
    ]

    operations = [
        migrations.RunPython(set_pos),
    ]
