# Generated by Django 2.2 on 2019-10-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0057_auto_20190925_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypoint',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqpoints', to='legislation.Requirments'),
        ),
    ]
