# Generated by Django 2.2 on 2019-10-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0058_keypoint_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirments',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Full description'),
        ),
        migrations.AddField(
            model_name='requirments',
            name='nodescription',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Non Conformance description'),
        ),
    ]
