# Generated by Django 2.2 on 2019-10-11 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0059_auto_20191010_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationposition',
            name='req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqpos', to='legislation.Requirments'),
        ),
        migrations.AlterField(
            model_name='legistationposition',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locationpos', to='legislation.Location'),
        ),
        migrations.AlterField(
            model_name='legistationposition',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topicpos', to='legislation.Topic'),
        ),
    ]
