# Generated by Django 2.2 on 2019-10-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0063_auto_20191030_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
    ]
