# Generated by Django 2.2 on 2019-10-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0064_auto_20191030_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='published',
        ),
    ]
