# Generated by Django 2.2 on 2019-10-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0065_remove_category_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processesbuisnessactivities',
            options={'verbose_name': 'Process and Busines Activity', 'verbose_name_plural': 'Processes and Business Activities'},
        ),
    ]
