# Generated by Django 2.2 on 2019-11-06 00:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0066_auto_20191030_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislationtopic',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=4000, null=True, verbose_name='Full description'),
        ),
    ]
