# Generated by Django 2.2 on 2019-11-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0067_auto_20191106_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationtopicsresponse',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
