# Generated by Django 2.2 on 2019-11-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0068_legistationtopicsresponse_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keypoint',
            options={'ordering': ['id'], 'verbose_name': 'Key Point', 'verbose_name_plural': 'Key Points'},
        ),
    ]
