# Generated by Django 2.2 on 2019-11-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_company_category'),
        ('legislation', '0069_auto_20191107_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformanceOuterResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identified', models.TextField(max_length=2000, null=True, verbose_name='Identified by')),
                ('assigned', models.TextField(max_length=2000, null=True, verbose_name='Assigned to')),
                ('containment', models.TextField(max_length=2000, null=True, verbose_name='Containment actions')),
                ('completion', models.TextField(max_length=2000, null=True, verbose_name='Completion date & by whom')),
                ('root', models.TextField(max_length=2000, null=True, verbose_name='Root cause')),
                ('corrective', models.TextField(max_length=2000, null=True, verbose_name='Corrective actions')),
                ('cost', models.TextField(max_length=2000, null=True, verbose_name='Cost of nonconformance')),
                ('reviewed', models.TextField(max_length=2000, null=True, verbose_name='Reviewed and closed out by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyouternc', to='company.Company')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.SourceNC')),
            ],
            options={
                'verbose_name': 'Outer NC',
                'verbose_name_plural': 'Outer NC',
            },
        ),
    ]
