# Generated by Django 2.2 on 2019-11-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0070_nonconformanceouterresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformanceouterresponse',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
