# Generated by Django 2.2 on 2019-11-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0071_nonconformanceouterresponse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformanceouterresponse',
            name='initialrecord',
            field=models.BooleanField(default=False),
        ),
    ]
