# Generated by Django 2.2 on 2019-12-05 03:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0072_nonconformanceouterresponse_initialrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoint',
            name='point',
            field=models.CharField(max_length=600, verbose_name='Key Point'),
        ),
        migrations.AlterField(
            model_name='legislationtopiccomply',
            name='title',
            field=models.CharField(max_length=600, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='legislationtopicoption',
            name='option',
            field=models.CharField(max_length=600, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=4000, null=True, verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='name',
            field=models.CharField(max_length=600, verbose_name='Name'),
        ),
    ]
