# Generated by Django 2.2 on 2019-12-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0073_auto_20191205_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ord',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='topic',
            name='ord',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
