# Generated by Django 2.2 on 2019-12-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0074_auto_20191215_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['ord'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['ord'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
