# Generated by Django 2.2 on 2019-12-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0076_legislationtopic_sq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislationtopic',
            name='sq',
        ),
    ]
