# Generated by Django 2.2 on 2019-12-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0077_remove_legislationtopic_sq'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationtopicsresponse',
            name='ncnote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legistationnonconformanceresponse',
            name='assigned',
            field=models.TextField(max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
