# Generated by Django 2.2 on 2019-12-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0078_auto_20191229_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationnonconformanceresponse',
            name='ncdesc',
            field=models.TextField(max_length=2000, null=True, verbose_name='NC description'),
        ),
    ]
