# Generated by Django 2.2 on 2020-01-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0082_nonconformanceouterresponse_assign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislationtopiccomply',
            options={'ordering': ['id'], 'verbose_name': 'Comply option', 'verbose_name_plural': 'Comply option'},
        ),
    ]
