# Generated by Django 2.2 on 2020-01-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0083_auto_20200116_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislationtopiccomply',
            options={'ordering': ['created'], 'verbose_name': 'Comply option', 'verbose_name_plural': 'Comply option'},
        ),
        migrations.AddField(
            model_name='legislationtopiccomply',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
