# Generated by Django 2.2 on 2020-01-16 01:20

from django.db import migrations
from datetime import datetime, timedelta

def set_dates(apps, schema_editor):
    LegislationTopicComply = apps.get_model("legislation", "LegislationTopicComply")
    today = datetime.now()-timedelta(days=1)
    for l in LegislationTopicComply.objects.all().order_by('id'):
        l.created = today
        l.save()
        today = today+timedelta(minutes=10)


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0084_auto_20200116_0117'),
    ]

    operations = [
        migrations.RunPython(set_dates),
    ]
