# Generated by Django 2.2 on 2020-01-16 03:18

from django.db import migrations

def set_verified(apps, schema_editor):
    NonConformanceOuterResponse = apps.get_model("legislation", "NonConformanceOuterResponse")
    for l in NonConformanceOuterResponse.objects.all():
        v=False
        if l.source and l.identified and l.assigned and l.assigned and l.containment and l.completion and l.root and l.corrective and l.cost and l.reviewed:
            v=True
        l.verified = v
        l.save()

    LegistationNonConformanceResponse = apps.get_model("legislation", "LegistationNonConformanceResponse")

    for l in LegistationNonConformanceResponse.objects.all():
        v=False
        if l.source and l.identified and l.assigned and l.assigned and l.containment and l.completion and l.root and l.corrective and l.cost and l.reviewed:
            v=True
        l.verified = v
        l.save()

class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0086_auto_20200116_0318'),
    ]

    operations = [
        migrations.RunPython(set_verified),
    ]
