# Generated by Django 2.2 on 2020-01-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0087_auto_20200116_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationnonconformanceresponse',
            name='outer',
            field=models.BooleanField(default=False, editable=False, verbose_name='Outer'),
        ),
    ]
