# Generated by Django 2.2 on 2020-01-21 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legislation', '0088_legistationnonconformanceresponse_outer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legistationnonconformanceresponse',
            name='outer',
        ),
        migrations.CreateModel(
            name='NonConformanceOuterResponseStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identified', models.TextField(max_length=2000, null=True, verbose_name='Identified by')),
                ('assigned', models.TextField(max_length=2000, null=True, verbose_name='Assigned to')),
                ('containment', models.TextField(max_length=2000, null=True, verbose_name='Containment actions')),
                ('completion', models.TextField(max_length=2000, null=True, verbose_name='Completion date & by whom')),
                ('root', models.TextField(max_length=2000, null=True, verbose_name='Root cause')),
                ('corrective', models.TextField(max_length=2000, null=True, verbose_name='Corrective actions')),
                ('cost', models.TextField(max_length=2000, null=True, verbose_name='Cost of nonconformance')),
                ('reviewed', models.TextField(max_length=2000, null=True, verbose_name='Reviewed and closed out by')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Description')),
                ('verified', models.BooleanField(default=False, editable=False, verbose_name='Verified')),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislationouternc', to='legislation.Legislation')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.SourceNC')),
            ],
            options={
                'verbose_name': 'State of Outer NC',
                'verbose_name_plural': 'State of Outer NC',
            },
        ),
    ]
