# Generated by Django 2.2 on 2020-01-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0089_auto_20200121_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonconformanceouterresponsestates',
            old_name='description',
            new_name='desc',
        ),
    ]
