# Generated by Django 2.2 on 2020-02-02 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0090_auto_20200122_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformanceouterresponse',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Identified by'),
        ),
    ]
