# Generated by Django 2.2 on 2020-02-06 04:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0096_auto_20200203_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoint',
            name='point',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='Key Point'),
        ),
        migrations.AlterField(
            model_name='legislationtopiccomply',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='Title'),
        ),
    ]
