# Generated by Django 2.2 on 2020-02-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0098_auto_20200207_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegistationTopicsKeyPointResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpointresponse', to='legislation.KeyPoint')),
                ('topicresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicresponsekeyp', to='legislation.LegistationTopicsResponse')),
            ],
            options={
                'verbose_name_plural': 'Legislation key point responses',
                'verbose_name': 'Legislation key point response',
            },
        ),
    ]
