# Generated by Django 2.2 on 2020-02-12 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0099_legistationtopicskeypointresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legistationtopicskeypointresponse',
            unique_together={('topicresponse', 'point')},
        ),
    ]
