# Generated by Django 2.2 on 2020-02-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0100_auto_20200212_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legistationtopicskeypointresponse',
            name='note',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
