# Generated by Django 2.2 on 2020-02-19 00:58

import ckeditor.fields
from django.db import migrations

def load_version(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    s = Site.objects.all()
    s = s[0]

    Currency = apps.get_model("legislation", "Currency")
    Currency.objects.all().delete()

    h = Currency.objects.create(name="GBP", settings=s.site_settings,main=True)
    h = Currency.objects.create(name="EUR", settings=s.site_settings, main=False)


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0102_auto_20200219_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoint',
            name='point',
            field=ckeditor.fields.RichTextField(max_length=10000, verbose_name='Key Point'),
        ),
    ]
