# Generated by Django 2.2 on 2020-02-19 01:04

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0103_auto_20200219_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoint',
            name='point',
            field=django_bleach.models.BleachField(max_length=10000),
        ),
    ]
