# Generated by Django 2.2 on 2020-04-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0107_category_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationtopicskeypointresponse',
            name='response',
            field=models.IntegerField(blank=True, choices=[(1, 'Full Compliance'), (0, 'No Compliance')], null=True),
        ),
    ]
