# Generated by Django 2.2 on 2020-04-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0108_legistationtopicskeypointresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationtopicskeypointresponse',
            name='ncnote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
