# Generated by Django 2.2 on 2020-04-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0109_legistationtopicskeypointresponse_ncnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationnonconformanceresponse',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpointncresponse', to='legislation.KeyPoint'),
        ),
    ]
