# Generated by Django 2.2 on 2020-04-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0110_legistationnonconformanceresponse_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationVesrion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=120, verbose_name='Version')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('no', models.IntegerField(default=1, editable=False, unique=True, verbose_name='Order')),
            ],
            options={
                'ordering': ['no'],
                'verbose_name_plural': 'Vesrion',
                'verbose_name': 'Vesrion',
            },
        ),
    ]
