# Generated by Django 2.2 on 2020-04-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0111_legislationvesrion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegislationVesrion',
            new_name='LegislationVersion',
        ),
    ]
