# Generated by Django 2.2 on 2020-04-14 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0112_auto_20200414_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versionlegislations', to='legislation.LegislationVersion'),
        ),
        migrations.AddField(
            model_name='legislationtopic',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiontopics', to='legislation.LegislationVersion'),
        ),
    ]
