# Generated by Django 2.2 on 2020-04-14 01:58

from django.db import migrations

def load_version(apps, schema_editor):
    LegislationVersion = apps.get_model("legislation", "LegislationVersion")
    LegislationTopic = apps.get_model("legislation", "LegislationTopic")
    Legislation = apps.get_model("legislation", "Legislation")
    h = LegislationVersion.objects.create(version='1.0.0',name='Default version',published=True,no=1)

    for l in LegislationTopic.objects.all():
        l.version=h
        l.save()

    for l in Legislation.objects.all():
        l.version=h
        l.save()

class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0113_auto_20200414_0158'),
    ]

    operations = [
        migrations.RunPython(load_version),
    ]
