# Generated by Django 2.2 on 2020-04-14 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0114_version_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versionlegislations', to='legislation.LegislationVersion'),
        ),
        migrations.AlterField(
            model_name='legislationtopic',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiontopics', to='legislation.LegislationVersion'),
        ),
    ]
