# Generated by Django 2.2 on 2020-04-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0115_auto_20200414_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislationversion',
            options={'ordering': ['no'], 'verbose_name': 'Version', 'verbose_name_plural': 'Versions'},
        ),
    ]
