# Generated by Django 2.2 on 2020-04-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0116_auto_20200414_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislationversion',
            name='version',
            field=models.CharField(max_length=120, unique=True, verbose_name='Version'),
        ),
    ]
