# Generated by Django 2.2 on 2020-04-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0117_auto_20200414_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislationversion',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
