# Generated by Django 2.2 on 2020-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0118_auto_20200414_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislationversion',
            name='no',
            field=models.IntegerField(editable=False, null=True, unique=True, verbose_name='Order'),
        ),
    ]
