# Generated by Django 2.2 on 2020-04-15 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0120_auto_20200415_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypoint',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpchilds', to='legislation.KeyPoint'),
        ),
        migrations.AddField(
            model_name='legislationtopic',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topicchilds', to='legislation.LegislationTopic'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionchilds', to='legislation.Question'),
        ),
    ]
