# Generated by Django 2.2 on 2020-04-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0122_version_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('file', models.FileField(max_length=2000, upload_to='guidance/%Y/%m/%d/', verbose_name='File')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Guidance',
                'verbose_name_plural': 'Guidance',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Show for free'),
        ),
        migrations.AddField(
            model_name='legislationtopic',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Show for free'),
        ),
        migrations.AlterField(
            model_name='legislationversion',
            name='no',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Order'),
        ),
    ]
