# Generated by Django 2.2 on 2020-04-17 02:54

from django.db import migrations

def load_version(apps, schema_editor):
    LegislationVersion = apps.get_model("legislation", "LegislationVersion")
    Legislation = apps.get_model("legislation", "Legislation")
    Company = apps.get_model("company", "Company")
    h = LegislationVersion.objects.get(version='1.0.0')
    Legislation.objects.all().update(version=h)
    Company.objects.all().update(version=h)

class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0124_version_process'),
        ('company', '0045_company_version'),
    ]

    operations = [
        migrations.RunPython(load_version),
    ]
