# Generated by Django 2.2 on 2020-04-27 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legislation', '0128_auto_20200421_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformanceouterresponsestates',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncouterstatecompleted', to=settings.AUTH_USER_MODEL, verbose_name='Identified by'),
        ),
        migrations.AddField(
            model_name='nonconformanceouterresponsestates',
            name='completeddate',
            field=models.DateField(null=True, verbose_name='Completion date'),
        ),
        migrations.AddField(
            model_name='nonconformanceouterresponsestates',
            name='identified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncouterstateidentified', to=settings.AUTH_USER_MODEL, verbose_name='Identified by'),
        ),
        migrations.AddField(
            model_name='nonconformanceouterresponsestates',
            name='priority',
            field=models.CharField(choices=[(1, 'Low'), (0, 'Medium'), (0, 'High')], default=1, max_length=15, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='nonconformanceouterresponsestates',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncouterstatereviewed', to=settings.AUTH_USER_MODEL, verbose_name='Identified by'),
        ),
        migrations.AddField(
            model_name='nonconformanceouterresponsestates',
            name='revieweddate',
            field=models.DateField(null=True, verbose_name='Review date'),
        ),
    ]
