# Generated by Django 2.2 on 2020-04-27 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0129_auto_20200427_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformanceouterresponse',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outersources', to='legislation.SourceNC'),
        ),
    ]
