# Generated by Django 2.2 on 2020-04-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0130_auto_20200427_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationnonconformanceresponse',
            name='topicpos',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
