# Generated by Django 2.2 on 2020-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0132_auto_20200428_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legistationnonconformanceresponse',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=15, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='nonconformanceouterresponse',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=15, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='nonconformanceouterresponsestates',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=15, verbose_name='Priority'),
        ),
    ]
