# Generated by Django 2.2 on 2020-05-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0133_auto_20200429_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='desc',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Description'),
        ),
    ]
