# Generated by Django 2.2 on 2020-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0135_legislationtopic_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcenc',
            name='default',
            field=models.BooleanField(default=False, verbose_name='For Legal register'),
        ),
        migrations.AlterField(
            model_name='sourcenc',
            name='defaulto',
            field=models.BooleanField(default=False, verbose_name='For Outer NC'),
        ),
    ]
