# Generated by Django 2.2 on 2020-05-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0136_auto_20200506_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcenc',
            options={'ordering': ['name'], 'verbose_name': 'NC Sources', 'verbose_name_plural': 'NC Sources'},
        ),
    ]
