# Generated by Django 2.2 on 2020-05-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0137_auto_20200506_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='guidance',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
