# Generated by Django 2.2 on 2020-05-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0138_auto_20200508_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legistationnonconformanceresponse',
            options={'ordering': ['started'], 'verbose_name': 'NC', 'verbose_name_plural': 'NC'},
        ),
        migrations.AlterModelOptions(
            name='nonconformanceouterresponse',
            options={'ordering': ['started'], 'verbose_name': 'Outer NC', 'verbose_name_plural': 'Outer NC'},
        ),
    ]
