# Generated by Django 2.2 on 2020-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0139_auto_20200519_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislationtopic',
            name='orderfull',
            field=models.PositiveIntegerField(default=1, verbose_name='Order for full'),
        ),
        migrations.AlterField(
            model_name='legislationtopic',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Order for free'),
        ),
    ]
