# Generated by Django 2.2 on 2020-05-28 12:27

from django.db import migrations

def load_no(apps, schema_editor):
    Company = apps.get_model("company", "Company")
    LegistationNonConformanceResponse = apps.get_model("legislation", "LegistationNonConformanceResponse")
    Legislation = apps.get_model("legislation", "Legislation")
    for c in Company.objects.all():
        leg = Legislation.objects.filter(finished=False, company=c).first()
        if leg:
            no=1
            for nc in LegistationNonConformanceResponse.objects.filter(topicreply__position__legislation=leg).order_by("started"):
                nc.no=no
                nc.save()
                no+=1

            for nc in c.companyouternc.all().order_by("started"):
                nc.no = no
                nc.save()
                no += 1

class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0141_auto_20200528_0946'),
    ]

    operations = [
        migrations.RunPython(load_no),
    ]
