# Generated by Django 2.2 on 2020-06-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0144_auto_20200615_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True, verbose_name='Name')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('stripeId', models.CharField(blank=True, max_length=400, null=True, verbose_name='Stripe')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat', to='legislation.PriceSettings')),
            ],
            options={
                'verbose_name': 'VAT Rate',
                'verbose_name_plural': 'VAT Rates',
                'ordering': ['name'],
            },
        ),
    ]
