# Generated by Django 2.2 on 2020-06-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0145_vatrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatrate',
            name='stripeId',
            field=models.CharField(blank=True, editable=False, max_length=400, null=True, verbose_name='Stripe'),
        ),
    ]
