# Generated by Django 2.2 on 2020-06-16 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0146_auto_20200616_1331'),
    ]

    operations = [
    ]
