# Generated by Django 2.2 on 2020-06-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0148_remove_location_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation.VATRate'),
        ),
    ]
