# Generated by Django 2.2 on 2020-06-17 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0149_location_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatrate',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Value'),
        ),
    ]
