# Generated by Django 2.2 on 2020-07-02 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0150_auto_20200617_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodes',
            name='size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Size [%]'),
        ),
    ]
