# Generated by Django 2.2 on 2020-07-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0152_auto_20200702_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcodes',
            name='used',
            field=models.BooleanField(default=False, editable=False, verbose_name='Used'),
        ),
    ]
