# Generated by Django 2.2 on 2020-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0153_discountcodes_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodes',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
