# Generated by Django 2.2 on 2020-07-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0154_auto_20200703_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='legistationtopicsresponse',
            name='state',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
