# Generated by Django 2.2 on 2020-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0155_legistationtopicsresponse_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legistationtopicsresponse',
            name='state',
        ),
        migrations.AddField(
            model_name='legistationtopicsresponse',
            name='status',
            field=models.IntegerField(choices=[(1, 'Full Compliance'), (0, 'No Compliance'), (2, 'Partial Compliance')], default=0, editable=False),
        ),
    ]
