# Generated by Django 2.2 on 2020-07-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0157_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legistationtopicsresponse',
            name='status',
            field=models.IntegerField(choices=[(1, 'No Compliance'), (2, 'Incomplete'), (3, 'Full Compliance')], default=0, editable=False),
        ),
    ]
