# Generated by Django 2.2 on 2021-01-29 13:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0159_auto_20200717_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislation',
            name='version',
        ),
        migrations.RemoveField(
            model_name='legislationtopic',
            name='nodescription',
        ),
        migrations.RemoveField(
            model_name='legislationtopic',
            name='parent',
        ),
        migrations.AlterField(
            model_name='keypoint',
            name='point',
            field=ckeditor.fields.RichTextField(max_length=60000, verbose_name='Key Point'),
        ),
        migrations.AlterField(
            model_name='legislationtopic',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=60000, null=True, verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='legislationtopic',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='legislationtopiccomply',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=60000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='requirments',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=60000, null=True, verbose_name='Full description'),
        ),
        migrations.DeleteModel(
            name='LegislationVersion',
        ),
    ]
