# Generated by Django 2.2 on 2021-01-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0071_remove_company_version'),
        ('legislation', '0160_auto_20210129_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirments',
            new_name='Requirements',
        ),
    ]
