# Generated by Django 2.2 on 2021-01-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0161_auto_20210129_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegistationPosition',
            new_name='LegislationPosition',
        ),
    ]
