# Generated by Django 2.2 on 2021-01-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0163_auto_20210129_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegistationTopicsResponse',
            new_name='LegislationTopicsResponse',
        ),
    ]
