# Generated by Django 2.2 on 2021-01-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0164_auto_20210129_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegistationTopicsKeyPointResponse',
            new_name='LegislationTopicsKeyPointResponse',
        ),
    ]
