# Generated by Django 2.2 on 2021-01-29 14:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legislation', '0165_auto_20210129_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegistationNonConformanceResponse',
            new_name='LegislationNonConformanceResponse',
        ),
    ]
