# Generated by Django 2.2 on 2021-02-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0072_remove_company_pba'),
        ('legislation', '0167_auto_20210129_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessesBuisnessActivities',
        ),
    ]
