# Generated by Django 3.1.8 on 2021-04-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0072_remove_company_pba'),
        ('legislation', '0168_delete_processesbuisnessactivities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Legislation',
            new_name='Register',
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['-finished'], 'verbose_name': 'Legal Register', 'verbose_name_plural': 'Legal Registers'},
        ),
        migrations.RenameField(
            model_name='legislationposition',
            old_name='legislation',
            new_name='register',
        ),
    ]
