# Generated by Django 2.2 on 2019-04-24 02:31

import armour.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190424_0222'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', armour.user.models.UserManager()),
            ],
        ),
    ]
