# Generated by Django 2.2 on 2019-04-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_country'),
        ('user', '0008_auto_20190424_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyusers', to='company.Company'),
        ),
    ]
