# Generated by Django 2.2 on 2020-03-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='Terms'),
        ),
    ]
