# Generated by Django 2.2 on 2020-03-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_lnk',
            field=models.BooleanField(default=False, verbose_name='Activate link'),
        ),
    ]
