# Generated by Django 2.2 on 2020-03-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_activate_lnk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='By signing up you agree to our Terms & Conditions and Privacy Policy.'),
        ),
    ]
