# Generated by Django 2.2 on 2019-05-06 05:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(max_length=4000, verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Tips',
                'verbose_name': 'Tip',
            },
        ),
    ]
