# Generated by Django 2.2 on 2019-09-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
