# Generated by Django 2.2 on 2019-09-06 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0030_auto_20190905_0405'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0002_tip_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
                ('content', models.TextField(null=True, verbose_name='Email edit')),
                ('locations', models.ManyToManyField(blank=True, to='legislation.Location', verbose_name='Locations')),
                ('sender', models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('sent_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Receivers')),
                ('topics', models.ManyToManyField(blank=True, to='legislation.Topic', verbose_name='Topics')),
            ],
        ),
    ]
