# Generated by Django 2.2 on 2019-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_massemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemail',
            name='content',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
    ]
