# Generated by Django 2.2 on 2019-09-10 00:24

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0004_auto_20190909_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massemail',
            name='sender',
        ),
        migrations.AddField(
            model_name='massemail',
            name='sender',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
