# Generated by Django 2.2 on 2019-09-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20190910_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['name'], 'verbose_name': 'Tip', 'verbose_name_plural': 'Tips'},
        ),
    ]
