# Generated by Django 2.2 on 2019-11-06 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20190924_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['name'], 'verbose_name': 'Help', 'verbose_name_plural': 'Help'},
        ),
    ]
