# Generated by Django 2.2 on 2020-03-23 03:45

from django.db import migrations

def term_page(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    s = Site.objects.all()
    s = s[0]

    FlatPage = apps.get_model("flatpages", "FlatPage")
    page = FlatPage.objects.create(url="/terms/",content='',title="Terms")
    page.sites.add(s)

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20191106_0023'),
    ]

    operations = [
        migrations.RunPython(term_page),
    ]
