# Generated by Django 2.2 on 2020-04-27 00:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0128_auto_20200421_0452'),
        ('general', '0008_auto_20200323_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='massemail',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislation.LegislationVersion'),
        ),
        migrations.AlterField(
            model_name='massemail',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=4000, verbose_name='Content'),
        ),
    ]
