# Generated by Django 2.2 on 2020-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20200427_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True, verbose_name='Name')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('stripeId', models.CharField(blank=True, max_length=400, null=True, verbose_name='Stripe')),
            ],
            options={
                'verbose_name': 'VAT Rate',
                'verbose_name_plural': 'VAT Rates',
                'ordering': ['name'],
            },
        ),
    ]
