# Generated by Django 2.2 on 2020-06-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_vatrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VATRate',
        ),
    ]
