# Generated by Django 2.2 on 2021-01-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_delete_vatrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massemail',
            name='version',
        ),
    ]
