# Generated by Django 2.2 on 2019-04-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Company name')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('zipcode', models.CharField(max_length=20, verbose_name='ZIP Code')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('email', models.EmailField(max_length=400, verbose_name='Email')),
                ('website', models.URLField(max_length=400, null=True, verbose_name='Website')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
