# Generated by Django 2.2 on 2019-06-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0018_auto_20190509_0048'),
        ('company', '0004_auto_20190519_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(blank=True, to='legislation.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='company',
            name='topics',
            field=models.ManyToManyField(blank=True, to='legislation.Topic', verbose_name='Topics'),
        ),
    ]
