# Generated by Django 2.2 on 2019-07-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190624_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vat',
            field=models.CharField(max_length=200, null=True, verbose_name='VAT number'),
        ),
        migrations.CreateModel(
            name='CompanyCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc4', models.CharField(max_length=4, verbose_name='CC digit')),
                ('stripe_id', models.CharField(max_length=1000, null=True, verbose_name='City')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('surname', models.CharField(max_length=400, verbose_name='Surname')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='copmanycc')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
    ]
