# Generated by Django 2.2 on 2019-07-30 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190726_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycc',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='copmanycc'),
        ),
    ]
