# Generated by Django 2.2 on 2019-07-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190730_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billcity',
            field=models.CharField(max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='billstreet',
            field=models.CharField(max_length=200, null=True, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='company',
            name='billzipcode',
            field=models.CharField(max_length=20, null=True, verbose_name='ZIP Code'),
        ),
    ]
