# Generated by Django 2.2 on 2019-07-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_billcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycc',
            name='email',
            field=models.EmailField(max_length=400, null=True, verbose_name='Email'),
        ),
    ]
