# Generated by Django 2.2 on 2019-08-06 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20190806_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycc',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copmanycc', to='company.Company'),
        ),
    ]
