# Generated by Django 2.2 on 2019-08-06 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0021_currencys'),
        ('company', '0016_auto_20190806_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currencycompanies', to='legislation.Currency'),
        ),
    ]
