# Generated by Django 2.2 on 2019-08-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20190806_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='stripe_id',
            new_name='stripe_plan_id',
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_subs_id',
            field=models.CharField(max_length=1000, null=True, verbose_name='City'),
        ),
    ]
