# Generated by Django 2.2 on 2019-08-11 23:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0021_currencys'),
        ('company', '0019_auto_20190807_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislation.Location', verbose_name='Location')),
                ('payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payitems', to='company.Payments')),
                ('topics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislation.Topic', verbose_name='Topics')),
            ],
            options={
                'verbose_name': 'Payments position',
                'verbose_name_plural': 'Payments positions',
            },
        ),
    ]
