# Generated by Django 2.2 on 2019-08-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_paymentspositions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentspositions',
            old_name='payments',
            new_name='payment',
        ),
    ]
