# Generated by Django 2.2 on 2019-08-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_payments_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
