# Generated by Django 2.2 on 2019-08-14 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0022_processesbuisnessactivities_requirments_sector'),
        ('company', '0024_auto_20190812_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pba',
            field=models.ManyToManyField(blank=True, to='legislation.ProcessesBuisnessActivities', verbose_name='Company Processes and Business Activities'),
        ),
        migrations.AddField(
            model_name='company',
            name='req',
            field=models.ManyToManyField(blank=True, to='legislation.Requirments', verbose_name='Standard or Other Requirements'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companysectors', to='legislation.Sector', verbose_name='Sector'),
        ),
    ]
