# Generated by Django 2.2 on 2019-08-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_auto_20190814_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='scope',
            field=models.TextField(max_length=3000, null=True, verbose_name='Organisational scope'),
        ),
    ]
