# Generated by Django 2.2 on 2019-08-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='postion',
            new_name='position',
        ),
    ]
