# Generated by Django 2.2 on 2019-09-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20190821_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='companylocations', to='legislation.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='company',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='companytopics', to='legislation.Topic', verbose_name='Topics'),
        ),
    ]
