# Generated by Django 2.2 on 2019-09-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_auto_20190911_0051'),
        ('company', '0029_auto_20190911_0119'),
    ]

    operations = [
    ]
