# Generated by Django 2.2 on 2019-09-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_merge_20190911_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Website'),
        ),
    ]
