# Generated by Django 2.2 on 2019-09-26 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0057_auto_20190925_0604'),
        ('company', '0031_auto_20190924_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-date'], 'verbose_name': 'Payments', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payments',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legislation.Currency', verbose_name='Currency'),
        ),
    ]
