# Generated by Django 2.2 on 2019-09-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_auto_20190926_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='stripe_plan_id',
            field=models.CharField(max_length=1000, null=True, verbose_name='Plan ID'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='stripe_subs_id',
            field=models.CharField(max_length=1000, null=True, verbose_name='Subscription ID'),
        ),
    ]
