# Generated by Django 2.2 on 2019-09-26 05:05

from django.db import migrations

def set_currency(apps, schema_editor):
    Payments = apps.get_model("company", "Payments")
    for p in Payments.objects.all():
        p.currency = p.company.currency
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_auto_20190926_0505'),
    ]

    operations = [
        migrations.RunPython(set_currency),
    ]
