# Generated by Django 2.2 on 2020-03-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
