# Generated by Django 2.2 on 2020-03-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_auto_20200330_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(blank=True, to='legislation.Category', verbose_name='Sector'),
        ),
    ]
