# Generated by Django 2.2 on 2020-04-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_auto_20200330_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Free'),
        ),
    ]
