# Generated by Django 2.2 on 2020-04-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_company_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Free'),
        ),
    ]
