# Generated by Django 2.2 on 2020-04-15 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0119_auto_20200414_0520'),
        ('company', '0044_payments_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versioncompany', to='legislation.LegislationVersion'),
        ),
    ]
