# Generated by Django 2.2 on 2020-04-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_company_specqgenerated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='specqgenerated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Generated'),
        ),
    ]
