# Generated by Django 2.2 on 2020-04-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0049_auto_20200430_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='generate',
        ),
    ]
