# Generated by Django 2.2 on 2020-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0050_remove_company_generate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='selectplan',
            field=models.BooleanField(default=True, editable=False, verbose_name='Select plan'),
        ),
    ]
