# Generated by Django 2.2 on 2020-06-17 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0054_auto_20200528_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='tax',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='payments',
            name='total',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
    ]
