# Generated by Django 2.2 on 2020-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0057_payments_stripe_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='stripe_invoice_pdf',
            field=models.CharField(max_length=1000, null=True, verbose_name='Invoice PDF'),
        ),
    ]
