# Generated by Django 2.2 on 2020-06-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0058_payments_stripe_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='stripe_charge_id',
            field=models.CharField(max_length=1000, null=True, verbose_name='Invoice ID'),
        ),
    ]
