# Generated by Django 2.2 on 2020-06-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0059_payments_stripe_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='stripe_charge_id',
            field=models.CharField(editable=False, max_length=1000, null=True, verbose_name='Invoice ID'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='stripe_invoice_id',
            field=models.CharField(editable=False, max_length=1000, null=True, verbose_name='Invoice ID'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='stripe_plan_id',
            field=models.CharField(editable=False, max_length=1000, null=True, verbose_name='Plan ID'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='stripe_subs_id',
            field=models.CharField(editable=False, max_length=1000, null=True, verbose_name='Subscription ID'),
        ),
    ]
