# Generated by Django 2.2 on 2020-07-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0064_auto_20200703_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='refund',
            field=models.BooleanField(default=False, verbose_name='Refund'),
        ),
        migrations.AddField(
            model_name='payments',
            name='refunded',
            field=models.BooleanField(default=False, editable=False, verbose_name='Refunded'),
        ),
    ]
