# Generated by Django 2.2 on 2020-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0065_auto_20200715_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='refunddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Refund date'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_refund_id',
            field=models.CharField(editable=False, max_length=1000, null=True, verbose_name='Refund ID'),
        ),
    ]
