# Generated by Django 2.2 on 2020-07-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0066_auto_20200715_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='stripe_refund_charge_id',
            field=models.CharField(editable=False, max_length=1000, null=True, verbose_name='RefundCharge ID'),
        ),
    ]
