# Generated by Django 2.2 on 2020-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0067_payments_stripe_refund_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='stripe_refund_charge_id',
            field=models.CharField(editable=False, max_length=1000, null=True, verbose_name='Refund Charge ID'),
        ),
    ]
