# Generated by Django 2.2 on 2020-07-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0068_auto_20200715_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='refundreason',
            field=models.CharField(max_length=100, null=True, verbose_name='Refund Reason'),
        ),
    ]
