# Generated by Django 2.2 on 2021-01-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0070_remove_payments_refundreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='version',
        ),
    ]
