# Generated by Django 2.2 on 2021-02-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0071_remove_company_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='pba',
        ),
    ]
